name: Deploy React App

on:
  push:
    branches: [main]
    paths:
      - 'my-react-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: my-react-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: my-react-app

      - name: Build
        run: npm run build
        working-directory: my-react-app

      - name: List built files (for debugging)
        run: ls -la my-react-app/dist/
        working-directory: ./

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-react-app/dist
          destination_dir: my-react-app  # Thêm dòng này